### ISSUE TITLE
go test  paxos

### ISSUE THREAD

**Issue by happyer** [lichuang/paxos#1]
你这 paxos  测试不通过呢？

**Comment by lichuang** [comment]
错误信息贴一下我看看。

**Comment by happyer** [comment]
Test: Single proposer ...
--- FAIL: TestBasic (30.82s)
	test_test.go:64: too few decided; seq=0 ndecided=0 wanted=3

**Comment by lichuang** [comment]
你这是paxos目录下的用例，还是kvpaxos下面的用例？

**Comment by happyer** [comment]
paxos

**Comment by lichuang** [comment]
我测试了一下是可以的哦，你是cd到paxos目录执行的go test吗？

**Comment by happyer** [comment]
Cd arc 
go test -v paxos/ 
然后就报错，你是用的这个代码吗

**Comment by lichuang** [comment]
我是cd 到paxos目录执行 go test的，没有报错。我试了下你那个方式，确实有问题。但是换了我这样做就好了。

➜  src git:(master) ✗ cd paxos
➜  paxos git:(master) ✗ go test
2017/03/03 23:35:03 method Done has wrong number of ins: 2
2017/03/03 23:35:03 method Kill has wrong number of ins: 1
2017/03/03 23:35:03 method Max has wrong number of ins: 1
2017/03/03 23:35:03 method Min has wrong number of ins: 1
2017/03/03 23:35:03 method Start reply type not a pointer: interface {}
2017/03/03 23:35:03 method Status has wrong number of ins: 2
2017/03/03 23:35:03 method Done has wrong number of ins: 2
2017/03/03 23:35:03 method Kill has wrong number of ins: 1
2017/03/03 23:35:03 method Max has wrong number of ins: 1
2017/03/03 23:35:03 method Min has wrong number of ins: 1
2017/03/03 23:35:03 method Start reply type not a pointer: interface {}
2017/03/03 23:35:03 method Status has wrong number of ins: 2
2017/03/03 23:35:03 method Done has wrong number of ins: 2
2017/03/03 23:35:03 method Kill has wrong number of ins: 1
2017/03/03 23:35:03 method Max has wrong number of ins: 1
2017/03/03 23:35:03 method Min has wrong number of ins: 1
2017/03/03 23:35:03 method Start reply type not a pointer: interface {}
2017/03/03 23:35:03 method Status has wrong number of ins: 2
Test: Single proposer ...
  ... Passed

**Comment by happyer** [comment]
OK，因为我之前就是我那样测试的，你要进入才行的话，那也行咯
lichuang <notifications@github.com>于2017年3月3日 周五下午11:37写道：
